####################################
# RZ/G2L SBC board configurations
####################################

[rzg2l-sbc]
ethernet = ["11c20000", "11c30000"]
ethernet_udp_index = 1  
bl2_base = "0x12000"
fconf_dtb_base = "0x2A000"
# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzg2l-sbc.xspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

####################################
# RZ/G2L EVK board configurations
####################################

[rzg2l-evk]
ethernet = ["11c20000", "11c30000"]
ethernet_udp_index = 0
bl2_base = "0x12000"
fconf_dtb_base = "0x2A000"
# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzg2l-evk.xspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rzg2l-evk.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "FA", "810"]

# Bootloader flash eSD
[rzg2l-evk.esd]
BL2_BP_ESD = ["1", "1"]
BL2 = ["8"]
BID = ["250"]
FIP = ["256"]

####################################
# RS-G2L100 board configurations
####################################

[rs-g2l100]
ethernet = ["11c20000", "11c30000"]
ethernet_udp_index = ["0", "1"]
bl2_base = "0x12000"
fconf_dtb_base = "0x2A000"
# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rs-g2l100.xspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rs-g2l100.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "FA", "810"]

####################################
# RZ/V2L EVK board configurations
####################################

[rzv2l-evk]
ethernet = ["11c20000", "11c30000"]
ethernet_udp_index = 0
bl2_base = "0x12000"
fconf_dtb_base = "0x2A000"
# Uload bootloader
flash_address = ["00000", "1D200", "1C700"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzv2l-evk.xspi]
BL2 = ["11E00", "00000"]
FIP = ["00000", "1D200"]
BID = ["00810", "1C700"]

# Bootloader flash eMMC
[rzv2l-evk.emmc]
BL2 = ["1", "1", "11E00"]
FIP = ["1", "100", "00000", "2", "8"]
BID = ["1", "FA", "810"]

# Bootloader flash eSD
[rzv2l-evk.esd]
BL2_BP_ESD = ["1", "1"]
BL2 = ["8"]
BID = ["250"]
FIP = ["256"]

####################################
# RZ/V2H EVK board configurations
####################################

[rzv2h-evk]
ethernet = ["15c30000", "15c40000"]
ethernet_udp_index = ["0", "1"]
bl2_dest  = "0x08103000"
bl2_base = "0x8103000"
fconf_dtb_base = "0x08130000"

# Uload bootloader
flash_address = ["00000", "60000", "5F300"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzv2h-evk.xspi]
BL2 = ["8101E00", "00000"]
BID = ["00810", "5F300"]
FIP = ["00000", "60000"]

# Bootloader flash eMMC
[rzv2h-evk.emmc]
BL2 = ["1", "1", "8101E00"]
FIP = ["1", "300", "44000000", "2", "8"]
BID = ["1", "2FA", "810"]

# Bootloader flash eSD
[rzv2h-evk.esd]
BL2_BP_ESD = ["1", "1"]
BL2 = ["8"]
BID = ["762"]
FIP = ["768"]
####################################
# RZ/V2H RDK board configurations
####################################

[rzv2h-rdk]
ethernet = ["15c30000", "15c40000"]
ethernet_udp_index = 0
bl2_dest  = "0x08103000"
bl2_base = "0x8103000"
fconf_dtb_base = "0x08130000"

# Uload bootloader
flash_address = ["00000", "60000", "5F300"]
load_address = "0x48000000"

# Bootloader flash SPI
[rzv2h-rdk.xspi]
BL2 = ["8101E00", "00000"]
BID = ["00810", "5F300"]
FIP = ["00000", "60000"]

[rzv2h-rdk.emmc]
BL2 = ["1", "1", "8101E00"]
FIP = ["1", "300", "44000000", "2", "8"]
BID = ["1", "2FA", "810"]

# Bootloader flash eSD
[rzv2h-rdk.esd]
BL2_BP_ESD = ["1", "1"]
BL2 = ["8"]
BID = ["762"]
FIP = ["768"]

####################################
# IMDT V2H Single Board Computer configurations
####################################

[imdt-v2h-sbc]
ethernet = ["15c30000", "15c40000"]
ethernet_udp_index = ["0", "1"]
bl2_dest  = "0x08103000"
bl2_base = "0x8103000"
fconf_dtb_base = "0x08130000"

# Uload bootloader
flash_address = ["00000", "60000", "5F300"]
load_address = "0x48000000"

# Bootloader flash SPI
[imdt-v2h-sbc.xspi]
BL2 = ["8101E00", "00000"]
BID = ["00810", "5F300"]
FIP = ["00000", "60000"]

# Bootloader flash eMMC
[imdt-v2h-sbc.emmc]
BL2 = ["1", "1", "8101E00"]
FIP = ["1", "300", "44000000", "2", "8"]
BID = ["1", "2FA", "810"]

[sparrow-hawk]
ethernet = ["e6800000", "e6810000"]
ethernet_udp_index = "0"
spl_dest  = "0xEB210000"
fconf_dtb_base = "0x08130000"
uboot_load_address = "0x44100000"
load_address = "0x48000000"

[sparrow-hawk.uload]
verify_address = "0x49000000"
SPL = "00000"
UBOOT_FIT = "80000"
BID = "2C0000"
PCIE = "300000"
erase_size = "310000"
spl_max_size = "80000"
uboot_fit_max_size = "240000"
bid_size = "810"
pcie_max_size = "10000"

[sparrow-hawk.xspi]
SPL = ["EB210000", "00000"]
UBOOT_FIT = ["00000", "80000"]
PCIE = ["300000"]
BID = ["00810", "2C0000"]
